smartive-education/design-system-component-library-helloworld

- src/components/atoms/index.ts
- src/components/atoms/link/index.ts
- src/components/atoms/link/link.stories.tsx
- src/components/atoms/link/link.tsx
LinkComponent wurde hinzugefügt. (Es sollte erst der Button-PR gemerged werden.)
> Link Component

- tailwind.config.js
> fix: removed plugins outside of theme

- .dependency-cruiser.js
- tailwind.config.js
> fix: Changed to add base instead of component

- src/components/atoms/textfield/textfield.tsx
- src/components/molecules/card/card.stories.tsx
- src/components/molecules/card/card.tsx
- src/components/molecules/profile-header/profile-header.tsx
> feat: Finished card layout

- src/components/atoms/tabs/tabs.tsx
> feat: Added file upload to index file

- src/components/molecules/index.ts
- tailwind.config.js
> feat: add divider

- src/components/molecules/index.ts
- tailwind.config.js
Reverts smartive-education/design-system-component-library-helloworld#49
> Revert "feat: add divider"

- src/components/atoms/index.ts
- src/components/atoms/tabs/index.ts
- src/components/molecules/card/index.ts
- src/components/molecules/index.ts
- src/components/molecules/profile-header/index.ts
fix: Exported types and component
> feat: Make types and component public

- src/components/organisms/user-profile/user-profile.stories.tsx
- src/components/organisms/user-profile/user-profile.tsx
feat: Some changes. Removed image from profile user
> feat: Changed user profile by removing background image

- src/components/molecules/profile-header/profile-header.tsx
> fix: Further refactoring on file upload

- src/components/organisms/modal/modal.stories.tsx
- src/components/organisms/modal/modal.tsx
> fix: Refactored modal for app

- src/components/molecules/card/card.stories.tsx
- src/components/molecules/file-upload/file-upload.tsx
- src/components/molecules/profile-header/profile-header.stories.tsx
- src/components/organisms/modal/modal.tsx
fix: Refactored modal, file upload and profile header
> fix: Refactored modal, file upload and profile header

- src/components/molecules/file-upload/file-upload.stories.tsx
- src/components/molecules/file-upload/file-upload.tsx
> fix: Refactored file upload

- src/components/atoms/button/button.stories.tsx
- src/components/atoms/button/button.tsx
- src/components/molecules/file-upload/file-upload.stories.tsx
- src/components/molecules/file-upload/file-upload.tsx
- src/components/molecules/file-upload/index.ts
- src/components/molecules/index.ts
fix: refactored fileupload and disable button
> fix: Refactored file upload and button disable

- src/components/atoms/button/button.tsx
fix: added different color for disable button
> fix: Added different color for disable button

- src/components/molecules/file-upload/file-upload.tsx
> fix: Fixed files problem if no file is selected

- src/components/atoms/branding/branding-logo/branding-logo.tsx
> fix: fix build

- src/components/atoms/branding/branding-logo/branding-logo.tsx
> fix: fix default logo size

- src/components/organisms/modal/modal.tsx
> fix: Rearranged modal

- src/components/organisms/modal/modal.tsx
> fix: Rearranged modal part 2

- src/components/organisms/modal/modal.tsx
> fix: Rearranged modal part 3

- src/components/atoms/button/button.stories.tsx
- src/components/atoms/button/button.tsx
- src/components/molecules/profile-header/profile-header.tsx
> fix: Button for mobile view

- src/components/molecules/profile-header/profile-header.tsx
> fix: Profile header for

- src/components/organisms/user-profile/user-profile.tsx
- src/components/organisms/user-recommendation/user-recommendation.stories.tsx
- src/components/organisms/user-recommendation/user-recommendation.tsx
fix: Fix for next image component
> fix: Fix for next image component

- src/components/molecules/profile-header/profile-header.stories.tsx
- src/components/molecules/profile-header/profile-header.tsx
fix: Removed href from profile header
> fix: Removed href in profile header

- src/components/molecules/card/card.tsx
> fix: fixed card class

- src/components/atoms/interaction-button/interaction-button.tsx
> fix: fix label variant

- src/components/atoms/comment-button/comment-button.tsx
- src/components/atoms/interaction-button/interaction-button.tsx
> fix: make onClick optional

- src/components/atoms/interaction-button/interaction-button.tsx
fix: add cursor-pointer for label
> fix: add cursor-pointer for label

- src/components/molecules/file-upload/file-upload.tsx
fix: Added hidden for mobile file upload
> fix: added hidden for mobile file upload

- src/components/organisms/modal/modal.tsx
> fix: Refactored modal with md

- src/components/molecules/file-upload/file-upload.tsx
> fix: Refactored file upload md to sm
